name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node and Dependencies
        uses: actions/checkout@v4

      - name: Set up Node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        working-directory: ./OBSOverlays
        run: npm ci

      - name: Build
        working-directory: ./OBSOverlays
        run: npm run build